apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-back
  namespace: back-ns
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/back.log
      pos_file /var/log/fluentd/back.log.pos
      tag backend.log
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S%z
      </parse>
    </source>

    <match backend.log>
      @type stdout
    </match>

